name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests
        run: |
          cd server && npm ci && npm test
          cd ../client && npm ci && npm test

      - name: Build client
        run: cd client && npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/globaltechno_app/
            rm -rf server/node_modules client/node_modules
            git pull
            /home/ubuntu/.nvm/versions/node/v21.7.3/bin/npm ci --production --prefix server
            /home/ubuntu/.nvm/versions/node/v21.7.3/bin/npm ci --production --prefix client
            /home/ubuntu/.nvm/versions/node/v21.7.3/bin/pm2 restart all
